name: peloton-communicator-deployment 

on:
  push:
    branches:
      - main
      - dev
      - staging
    paths:
    # Directories/Locations for which a new build is required when a change is detected
      - app/**
      - backend/**
      - server/**
      - .github/**
  pull_request:
    branches: 
      - main
      - dev
      - staging

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - name: Flutter action
      uses: subosito/flutter-action@v2.6.1
    - uses: actions/checkout@v3
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
    - run: flutter --version
      working-directory: ./app
    - run: echo "executing deployment script for Flutter app"
      working-directory: ./app

  server:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - run: go version 
    - run: go test 
      working-directory: ./server/test
    - run: echo "executing deployment script for Server application"
      working-directory: ./server
